# Generated by Django 5.0.1 on 2024-02-28 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_page_create_date_page_update_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='daily_challenge',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
