# Generated by Django 5.0.1 on 2024-03-12 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_page_daily_challenge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='daily_challenge',
            field=models.CharField(blank=True, max_length=500, verbose_name='Daily challenge'),
        ),
    ]
